name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.7'
        cabal-version: '3.6.0.0'

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libsdl2-dev libglew-dev moreutils
        cabal update -j
        cabal install weeder hlint hindent stylish-haskell -j -z

    - name: Generate `cabal.project.local`
      run: "echo \"package * \n  ghc-options: -fwrite-ide-info\" > cabal.project.local"

    - name: Build
      run: |
        cabal clean # This is needed to run `weeder` correctly.
        cabal build --enable-tests --enable-benchmarks all -j

    - name: Detect unused lines
      run: ~/.cabal/bin/weeder

    - name: Run tests
      run: cabal test all -j

    - name: Run hlint
      run: ~/.cabal/bin/hlint .

    - name: Check format
      run: |
        find src tests app -name '*.hs'|xargs -I {} sh -c "cat {}|~/.cabal/bin/hindent|~/.cabal/bin/stylish-haskell|diff --color -u {} -"
